### ISSUE TITLE
State SSH fingerprint in documentation

### ISSUE THREAD

**Issue by stefan-apollo** [centerforaisafety/cluster-docs#23]
It would be great to be able to verify the SSH fingerprint when connecting to the cluster (for the first time).

When a user connects for the first time, their system usually asks:
```
ED25519 key fingerprint is SHA256:DiFgOsIH1WEUEDn6lg0ImIg7ok5RE+i4R26uxUhXjQA.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

Maybe add a line in the docs stating the fingerprint?

**Comment by steven-basart** [comment]
Thanks for the suggestion.  I added at the very top: 
https://github.com/centerforaisafety/cluster-docs/commit/217b1459c26beb4a9a15899dd04ca1bd03f581b4
